osx_image: xcode11.3
language: swift
#xcode_project: provaPods/provaPods.xcodeproj
#xcode_scheme: provaPods

notifications:
    email: false

script:
    - cd provaPods
    - bundle install
    - fastlane build
    - fastlane tests
