# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane
cocoapods

# classe, contenidor general
default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  
  # lane = mètode
  lane :tests do
    run_tests()
  end

  lane :build do
    build_ios_app(
      skip_archive: true,     
      skip_codesigning: true
    )
  end

end
